[package]
name = "subscriber"
version = "0.1.0"
edition = "2021"

[dependencies]
dust_dds = { workspace = true }
video_pubsub = { path = ".." }
ffmpeg-next = { workspace = true }
image = { workspace = true }
clap = { workspace = true}
